//
// Autogenerated by Thrift Compiler (0.15.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./test_types');
//HELPER FUNCTIONS AND STRUCTURES

var userService_test1_args = function(args) {
  this.length = null;
  this.width = null;
  this.hight = null;
  this.filename = null;
  if (args) {
    if (args.length !== undefined && args.length !== null) {
      this.length = args.length;
    }
    if (args.width !== undefined && args.width !== null) {
      this.width = args.width;
    }
    if (args.hight !== undefined && args.hight !== null) {
      this.hight = args.hight;
    }
    if (args.filename !== undefined && args.filename !== null) {
      this.filename = args.filename;
    }
  }
};
userService_test1_args.prototype = {};
userService_test1_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.length = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.width = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.hight = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.filename = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

userService_test1_args.prototype.write = function(output) {
  output.writeStructBegin('userService_test1_args');
  if (this.length !== null && this.length !== undefined) {
    output.writeFieldBegin('length', Thrift.Type.I32, 1);
    output.writeI32(this.length);
    output.writeFieldEnd();
  }
  if (this.width !== null && this.width !== undefined) {
    output.writeFieldBegin('width', Thrift.Type.I32, 2);
    output.writeI32(this.width);
    output.writeFieldEnd();
  }
  if (this.hight !== null && this.hight !== undefined) {
    output.writeFieldBegin('hight', Thrift.Type.I32, 3);
    output.writeI32(this.hight);
    output.writeFieldEnd();
  }
  if (this.filename !== null && this.filename !== undefined) {
    output.writeFieldBegin('filename', Thrift.Type.STRING, 4);
    output.writeString(this.filename);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var userService_test1_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
userService_test1_result.prototype = {};
userService_test1_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

userService_test1_result.prototype.write = function(output) {
  output.writeStructBegin('userService_test1_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var userServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
userServiceClient.prototype = {};
userServiceClient.prototype.seqid = function() { return this._seqid; };
userServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

userServiceClient.prototype.test1 = function(length, width, hight, filename, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_test1(length, width, hight, filename);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_test1(length, width, hight, filename);
  }
};

userServiceClient.prototype.send_test1 = function(length, width, hight, filename) {
  var output = new this.pClass(this.output);
  var params = {
    length: length,
    width: width,
    hight: hight,
    filename: filename
  };
  var args = new userService_test1_args(params);
  try {
    output.writeMessageBegin('test1', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

userServiceClient.prototype.recv_test1 = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new userService_test1_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('test1 failed: unknown result');
};
var userServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
userServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
userServiceProcessor.prototype.process_test1 = function(seqid, input, output) {
  var args = new userService_test1_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.test1.length === 4) {
    Q.fcall(this._handler.test1.bind(this._handler),
      args.length,
      args.width,
      args.hight,
      args.filename
    ).then(function(result) {
      var result_obj = new userService_test1_result({success: result});
      output.writeMessageBegin("test1", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("test1", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.test1(args.length, args.width, args.hight, args.filename, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new userService_test1_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("test1", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("test1", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
